### ISSUE TITLE
Inquiry about related publications

### ISSUE THREAD

**Issue by AimedarXie** [tnorthey/normal_mode_displacer#1]
I was wondering if there have been any academic publications related to this work? Reading such a paper would greatly help me understand the methods and context in more depth.

Thank you for your time and contributions!

**Comment by tnorthey** [comment]
It moves the molecule along its 3N-6 normal modes, which are an output from many quantum chemistry programs. In this one I just used Gaussian.

Just search online what molecule normal modes are, and that should help. Or in physical chemistry textbooks. I hope that helps.

Thanks for the comment!

**Comment by tnorthey** [comment]
Check here https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)/Spectroscopy/Vibrational_Spectroscopy/Vibrational_Modes/Normal_Modes

Scroll down a bit, here it calls the normal mode vectors Q. The code here simply moves the molecule along the vectors Q_1, Q_2, etc.
